# Компилятор и флаги
CC = gcc
CFLAGS = -g -std=c11 -Wall -Wextra -Iinclude
LDFLAGS = -lncurses

# Имя исполняемого файла
TARGET = my_program

# Директории
SRC_DIR = src
BUILD_DIR = build
INCLUDE_DIR = include

# Исходные файлы
SRCS = $(wildcard $(SRC_DIR)/*.c)

# Объектные файлы
OBJS = $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SRCS))

# Правило по умолчанию
all: $(BUILD_DIR)/$(TARGET)

# Сборка исполняемого файла
$(BUILD_DIR)/$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

# Компиляция каждого .c файла в .o
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Очистка проекта
clean:
	rm -rf $(BUILD_DIR)

# Запуск программы
run: $(BUILD_DIR)/$(TARGET)
	./$(BUILD_DIR)/$(TARGET)

# Псевдоцель (не создает файл)
.PHONY: all clean run
